
name: Bump version

# Controls when the workflow will run
on:
  push:
    branches: [ "develop" ]
  pull_request:
    types: 
      - closed
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # This 'if' ensuring the workflow only runs for merged PRs
    #  (avoid running when a PR is discarded - closed without merging)
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Github Tag Bump
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
